curl -XDELETE mrthn:8080/v2/apps/analytics/spark/zeppelin
curl -XDELETE mrthn:8080/v2/apps/analytics/messaging/kafka
curl -XDELETE mrthn:8080/v2/apps/analytics/spark/spark-worker1
curl -XDELETE mrthn:8080/v2/apps//analytics/hadoop/hbase-rs-01
curl -XDELETE mrthn:8080/v2/apps//analytics/hadoop/hbase-rs-02
curl -XDELETE mrthn:8080/v2/apps/analytics/spark/spark-master-1
curl -XDELETE mrthn:8080/v2/apps//analytics/hadoop/hbase-master-1
curl -XDELETE mrthn:8080/v2/apps//analytics/hadoop/hdfs-dn-02
curl -XDELETE mrthn:8080/v2/apps//analytics/hadoop/hdfs-dn-01
curl -XDELETE mrthn:8080/v2/apps//analytics/hadoop/hdfs-nn
