# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  # create aws node
  config.vm.define :aws do |aws_config|
      aws_config.vm.box = "bento/ubuntu-16.04"
      aws_config.vm.hostname = "aws"
      #aws_config.vm.network :private_network, ip: "172.0.15.10"
      aws_config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
      aws_config.vm.provision :shell, path: "scripts/bootstrap-aws.ubuntu.sh"
  end
end  
